name: "NUnit Reporter"
description: "Github action for publishing nunit results as github checks"
author: "MirageNet"
inputs:
  path:
    description: "glob to junit xml files"
    required: true
  numFailures:
    description: "max number of failed tests to include"
    required: false
    default: "30"
  reportTitle:
    description: "Report title"
    required: false
    default: "Test Report"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "check"
  color: "green"
